[package]
name = "people-lib"
version = "0.1.0"
authors = ["Tim <timothyhollabaugh@gmail.com>"]

[dependencies]
mysql = "14.1.1"
database-lib = {path = "../../database_lib"}
rpassword = "2.0.0"
rouille = "2.2.0"
serde = "1.0.80"
serde_derive = "1.0.80"